
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /build/app.css

# scripts loaded in the end of the body
scripts:
- /build/app.js
